import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${nunito.variable} ${nunito.className} antialiased`}
            >
                <Header />
                <main className="min-h-screen bg-zinc-50 dark:bg-black">
                    {children}
                </main>
                <footer className="flex items-center px-8 py-4">
                    Dev by lvd 2026
                </footer>
            </body>
        </html>
    );
}
